spring:
  application:
    name: applicant-services
server:
  port: 8081
  servlet:
    context-path: /applicants
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO
    com.czetsuyatech: DEBUG